# Generated by Django 2.1.1 on 2019-02-14 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sleepsite', '0002_auto_20190208_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sleepdata',
            old_name='blood_pressure',
            new_name='heart_rate',
        ),
    ]
