# Generated by Django 2.1.1 on 2019-03-21 21:55

from django.db import migrations, models
import sleepsite.models


class Migration(migrations.Migration):

    dependencies = [
        ('sleepsite', '0013_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=None, upload_to=sleepsite.models.path_and_rename),
        ),
    ]
