# Generated by Django 2.1.1 on 2019-02-14 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sleepsite', '0003_auto_20190214_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alarm',
            old_name='spotify_id',
            new_name='youtube_link',
        ),
    ]
