# Generated by Django 2.1.2 on 2019-02-08 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('alarm_time', models.DateTimeField(unique=True)),
                ('spotify_id', models.CharField(max_length=255)),
                ('volume', models.IntegerField()),
            ],
            options={
                'ordering': ('created_on',),
            },
        ),
        migrations.CreateModel(
            name='SleepData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oxygen_level', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('blood_pressure', models.IntegerField()),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
