# Generated by Django 2.1.2 on 2019-02-08 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleepsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='spotify_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='volume',
            field=models.IntegerField(default=5),
        ),
    ]
