# Generated by Django 2.1.1 on 2019-02-15 21:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sleepsite', '0004_auto_20190214_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sleepdata',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
