# Generated by Django 2.1.1 on 2019-02-28 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleepsite', '0011_auto_20190226_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_link', models.TextField()),
            ],
            options={
                'ordering': ('youtube_link',),
            },
        ),
    ]
