# Generated by Django 2.1.1 on 2019-03-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleepsite', '0014_auto_20190328_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='images/moon.jpg', upload_to='images/'),
        ),
    ]
